server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Elyor
    username: Elyor
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
